# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system_crawl.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1312, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(60, 60))
        self.label.setMaximumSize(QtCore.QSize(60, 60))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("red_logo.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 15, 100, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(420, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_start.setMaximumSize(QtCore.QSize(150, 50))
        self.pushButton_start.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("search_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_start.setIcon(icon)
        self.pushButton_start.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout.addWidget(self.pushButton_start)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_zoekfolder = QtWidgets.QLabel(self.centralwidget)
        self.label_zoekfolder.setObjectName("label_zoekfolder")
        self.horizontalLayout.addWidget(self.label_zoekfolder)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_images = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_images.setObjectName("radioButton_images")
        self.horizontalLayout_2.addWidget(self.radioButton_images)
        self.radioButton_videos = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_videos.setObjectName("radioButton_videos")
        self.horizontalLayout_2.addWidget(self.radioButton_videos)
        self.radioButton_anders = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_anders.setObjectName("radioButton_anders")
        self.horizontalLayout_2.addWidget(self.radioButton_anders)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.pushButton_to_xls = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_to_xls.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_to_xls.setObjectName("pushButton_to_xls")
        self.verticalLayout_2.addWidget(self.pushButton_to_xls)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.tableWidget_resultaat = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_resultaat.setObjectName("tableWidget_resultaat")
        self.tableWidget_resultaat.setColumnCount(5)
        self.tableWidget_resultaat.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_resultaat.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_resultaat.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_resultaat.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_resultaat.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_resultaat.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableWidget_resultaat)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1312, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Selecteer een crawl folder"))
        self.label_2.setText(_translate("MainWindow", "Crawl folder is:"))
        self.label_zoekfolder.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Filter op:"))
        self.radioButton_images.setText(_translate("MainWindow", "Afbeeldingen"))
        self.radioButton_videos.setText(_translate("MainWindow", "Video\'s"))
        self.radioButton_anders.setText(_translate("MainWindow", "Anders"))
        self.pushButton_to_xls.setText(_translate("MainWindow", "Exporteer data als Excel"))
        self.tableWidget_resultaat.setSortingEnabled(True)
        item = self.tableWidget_resultaat.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Folder"))
        item = self.tableWidget_resultaat.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sequence"))
        item = self.tableWidget_resultaat.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Aantal files"))
        item = self.tableWidget_resultaat.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Size"))
        item = self.tableWidget_resultaat.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Totaal in bytes"))
